language: php
php:
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4snapshot'
install:
    composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage/report/coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
